import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Inspection, OCRResponse } from '../types';
import { validateOCRResponse } from '../engine/ocr';
export const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || 'http://localhost:5000';
export const supabaseConfigError = 'Supabase is not configured. Add both VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY to enable account storage.';
const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseKey = import.meta.env.VITE_SUPABASE_ANON_KEY;
const configuredSupabase = supabaseUrl && supabaseKey && !supabaseUrl.includes('PLACEHOLDER') ? createClient(supabaseUrl, supabaseKey) : null;
export function getSupabase(): SupabaseClient | null { return configuredSupabase; }
async function authenticatedClient() { const client = getSupabase(); if (!client) throw new Error(supabaseConfigError); const { data, error } = await client.auth.getUser(); if (error || !data.user) throw new Error('You must be signed in to access saved records.'); return { client, userId: data.user.id }; }
export async function uploadOCR(file: File): Promise<OCRResponse> { const extension = file.name.toLowerCase().split('.').pop(); if (!['image/jpeg','image/png','image/webp'].includes(file.type) && !['jpg','jpeg','png','webp'].includes(extension ?? '')) throw new Error('Use a JPG, JPEG, PNG, or WEBP image.'); if (file.size > 10 * 1024 * 1024) throw new Error('Images must be 10MB or smaller.'); const body = new FormData(); body.append('image', file); const response = await fetch(`${API_BASE_URL}/api/ocr`, { method: 'POST', body }); if (!response.ok) throw new Error(`OCR service failed (${response.status}).`); return validateOCRResponse(await response.json()); }
export async function saveInspection(inspection: Inspection): Promise<Inspection> { if (inspection.demo) throw new Error('Demonstration data cannot be saved as a real inspection. Upload a real label to save.'); const { client, userId } = await authenticatedClient(); const { error } = await client.from('inspections').insert({ id: inspection.id, user_id: userId, created_at: inspection.createdAt, image_name: inspection.imageName, image_data_url: inspection.imageDataUrl, ocr: inspection.ocr, fields: inspection.fields, rules: inspection.rules, summary: inspection.summary }); if (error) throw new Error(error.message); const [declarations, violations] = await Promise.all([client.from('declarations').insert(inspection.fields.map((field) => ({ inspection_id: inspection.id, user_id: userId, text: `${field.label}: ${field.value}`, created_at: inspection.createdAt }))), client.from('violations').insert(inspection.rules.filter((rule) => rule.status !== 'COMPLIANT').map((rule) => ({ inspection_id: inspection.id, user_id: userId, rule_id: rule.id, status: rule.status, note: rule.reason })))]);
  if (declarations.error) throw new Error(declarations.error.message);
  if (violations.error) throw new Error(violations.error.message);
  return inspection; }
function mapInspection(r: Record<string, unknown>): Inspection { return { id: r.id as string, userId: r.user_id as string, createdAt: r.created_at as string, imageName: r.image_name as string, imageDataUrl: r.image_data_url as string | undefined, ocr: r.ocr as Inspection['ocr'], fields: r.fields as Inspection['fields'], rules: r.rules as Inspection['rules'], summary: r.summary as Inspection['summary'] }; }
export async function listInspections(): Promise<Inspection[]> { const { client, userId } = await authenticatedClient(); const { data, error } = await client.from('inspections').select('*').eq('user_id', userId).order('created_at', { ascending: false }); if (error) throw new Error(error.message); return (data ?? []).map((row) => mapInspection(row as Record<string, unknown>)); }
export async function fetchInspection(id: string) { const { client, userId } = await authenticatedClient(); const { data, error } = await client.from('inspections').select('*').eq('id', id).eq('user_id', userId).maybeSingle(); if (error) throw new Error(error.message); return data ? mapInspection(data as Record<string, unknown>) : null; }
export async function deleteInspection(id: string) { const { client, userId } = await authenticatedClient(); const { error } = await client.from('inspections').delete().eq('id', id).eq('user_id', userId); if (error) throw new Error(error.message); }
export async function fetchDeclaration(id: string) { const { client, userId } = await authenticatedClient(); const { data, error } = await client.from('declarations').select('*').eq('id', id).eq('user_id', userId).maybeSingle(); if (error) throw new Error(error.message); return data; }
export async function listViolations(inspectionId: string) { const { client, userId } = await authenticatedClient(); const { data, error } = await client.from('violations').select('*').eq('inspection_id', inspectionId).eq('user_id', userId); if (error) throw new Error(error.message); return data ?? []; }
export async function saveDeclaration(declaration: { id: string; inspectionId: string; text: string; createdAt: string }) { const { client, userId } = await authenticatedClient(); const { error } = await client.from('declarations').insert({ id: declaration.id, inspection_id: declaration.inspectionId, user_id: userId, text: declaration.text, created_at: declaration.createdAt }); if (error) throw new Error(error.message); return declaration; }
export async function saveViolation(violation: { id: string; inspectionId: string; ruleId: string; status: string; note: string }) { const { client, userId } = await authenticatedClient(); const { error } = await client.from('violations').insert({ id: violation.id, inspection_id: violation.inspectionId, user_id: userId, rule_id: violation.ruleId, status: violation.status, note: violation.note }); if (error) throw new Error(error.message); return violation; }
export async function deleteViolation(id: string) { const { client, userId } = await authenticatedClient(); const { error } = await client.from('violations').delete().eq('id', id).eq('user_id', userId); if (error) throw new Error(error.message); }
