import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Inspection, OCRResponse } from '../types';
import { validateOCRResponse } from '../engine/ocr';
export const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || 'http://localhost:5000';
export function getSupabase(): SupabaseClient | null { const url = import.meta.env.VITE_SUPABASE_URL; const key = import.meta.env.VITE_SUPABASE_ANON_KEY; return url && key ? createClient(url, key) : null; }
export const supabaseConfigError = 'Supabase is not configured. Add both VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY to enable account storage.';
export async function uploadOCR(file: File): Promise<OCRResponse> { if (!['image/jpeg','image/png','image/webp'].includes(file.type)) throw new Error('Use a JPG, JPEG, PNG, or WEBP image.'); if (file.size > 10 * 1024 * 1024) throw new Error('Images must be 10MB or smaller.'); const body = new FormData(); body.append('image', file); const response = await fetch(`${API_BASE_URL}/api/ocr`, { method: 'POST', body }); if (!response.ok) throw new Error(`OCR service failed (${response.status}).`); return validateOCRResponse(await response.json()); }
export async function saveInspection(inspection: Inspection): Promise<Inspection> { const client = getSupabase(); if (!client) throw new Error(supabaseConfigError); const { error } = await client.from('inspections').insert({ id: inspection.id, created_at: inspection.createdAt, image_name: inspection.imageName, ocr: inspection.ocr, fields: inspection.fields, rules: inspection.rules, summary: inspection.summary }); if (error) throw new Error(error.message); return inspection; }
export async function listInspections(): Promise<Inspection[]> { const client = getSupabase(); if (!client) throw new Error(supabaseConfigError); const { data, error } = await client.from('inspections').select('*').order('created_at', { ascending: false }); if (error) throw new Error(error.message); return (data ?? []).map((r) => ({ id: r.id, createdAt: r.created_at, imageName: r.image_name, ocr: r.ocr, fields: r.fields, rules: r.rules, summary: r.summary } as Inspection)); }
export async function fetchInspection(id: string) { const items = await listInspections(); return items.find((item) => item.id === id) ?? null; }
export async function deleteInspection(id: string) { const client = getSupabase(); if (!client) throw new Error(supabaseConfigError); const { error } = await client.from('inspections').delete().eq('id', id); if (error) throw new Error(error.message); }
export async function saveDeclaration(declaration: { id: string; inspectionId: string; text: string; createdAt: string }) { const client = getSupabase(); if (!client) throw new Error(supabaseConfigError); const { error } = await client.from('declarations').insert({ id: declaration.id, inspection_id: declaration.inspectionId, text: declaration.text, created_at: declaration.createdAt }); if (error) throw new Error(error.message); return declaration; }
export async function saveViolation(violation: { id: string; inspectionId: string; ruleId: string; status: string; note: string }) { const client = getSupabase(); if (!client) throw new Error(supabaseConfigError); const { error } = await client.from('violations').insert({ id: violation.id, inspection_id: violation.inspectionId, rule_id: violation.ruleId, status: violation.status, note: violation.note }); if (error) throw new Error(error.message); return violation; }
export async function listViolations(inspectionId: string) { const client = getSupabase(); if (!client) throw new Error(supabaseConfigError); const { data, error } = await client.from('violations').select('*').eq('inspection_id', inspectionId); if (error) throw new Error(error.message); return data ?? []; }
export async function fetchDeclaration(id: string) { const client = getSupabase(); if (!client) throw new Error(supabaseConfigError); const { data, error } = await client.from('declarations').select('*').eq('id', id).maybeSingle(); if (error) throw new Error(error.message); return data; }
export async function deleteViolation(id: string) { const client = getSupabase(); if (!client) throw new Error(supabaseConfigError); const { error } = await client.from('violations').delete().eq('id', id); if (error) throw new Error(error.message); }
